org.gradle.jvmargs=-Xmx4G
minecraft_version=1.21.1
archives_base_name=reterraforged
mod_version=0.0.6005
mod_id=reterraforged
maven_group=raccoonman.reterraforged
fabric_loader_version=0.19.3
fabric_api_version=0.102.0+1.21.1
neoforge_version=21.1.219
terrablender_version=4.1.0.0
architectury_version=13.0.8
