plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    
    runs {
        client {
            ideConfigGenerated(true)
        }
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven { url "https://maven.neoforged.net/releases/" }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"
    modCompileOnly "maven.modrinth:biolith:3.0.14-neoforge"
}

repositories {
    maven { url "https://api.modrinth.com/maven" }
}

evaluationDependsOn(':common')

processResources {

    from project(":common").file("src/main/resources")

	inputs.property "neoforgeVersion", "21.1.201"
    inputs.property "version", project.version

    // Prevent duplicate file errors if files exist in multiple places
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
		expand "neoforgeVersion": "21.1.201"
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("shadow")
}

remapJar {
    atAccessWideners.add('reterraforged.accesswidener')

    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

jar {
    archiveClassifier.set("dev")
}

processResources {
    duplicatesStrategy "exclude"
}

sourcesJar {
    duplicatesStrategy "exclude"
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
